// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: '常用工具',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'src/pages/pdf-multi-tool.html',
        name: 'PDF多功能工具',
        icon: 'pencil-ruler',
        subtitle: '在统一界面中合并、拆分、组织、删除、旋转、添加空白页、提取和复制。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/merge-pdf.html',
        name: '合并PDF',
        icon: 'combine',
        subtitle: '将多个PDF合并为一个文件。保留书签。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/split-pdf.html',
        name: '拆分PDF',
        icon: 'scissors',
        subtitle: '将页面范围提取到新的PDF中。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/compress-pdf.html',
        name: '压缩PDF',
        icon: 'zap',
        subtitle: '减小PDF文件大小。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/edit-pdf.html',
        name: 'PDF编辑器',
        icon: 'pocket-knife',
        subtitle:
          '注释、高亮、编辑、评论、添加形状/图像、搜索和查看PDF',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/jpg-to-pdf.html',
        name: 'JPG转PDF',
        icon: 'image-up',
        subtitle: '从一个或多个JPG图像创建PDF。',
      },
      {
        id: 'sign-pdf',
        name: '签名PDF',
        icon: 'pen-tool',
        subtitle: '绘制、输入或上传您的签名。',
      },
      {
        id: 'cropper',
        name: '裁剪PDF',
        icon: 'crop',
        subtitle: '修剪PDF每一页的边距。',
      },
      {
        id: 'extract-pages',
        name: '提取页面',
        icon: 'ungroup',
        subtitle: '将选定的页面保存为新文件。',
      },
      {
        id: 'duplicate-organize',
        name: '复制和整理',
        icon: 'files',
        subtitle: '复制、重新排序和删除页面。',
      },
      {
        id: 'delete-pages',
        name: '删除页面',
        icon: 'trash-2',
        subtitle: '从文档中删除特定页面。',
      },
    ],
  },
  {
    name: '编辑和注释',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'src/pages/edit-pdf.html',
        name: 'PDF编辑器',
        icon: 'pocket-knife',
        subtitle:
          '注释、高亮、编辑、评论、添加形状/图像、搜索和查看PDF。',
      },
      {
        // id: 'bookmark-pdf',
        href: import.meta.env.BASE_URL + 'src/pages/bookmark.html',
        name: '编辑书签',
        icon: 'bookmark',
        subtitle: '添加、编辑、导入、删除和提取PDF书签。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/table-of-contents.html',
        name: '目录',
        icon: 'list',
        subtitle: '从PDF书签生成目录页。',
      },
      {
        id: 'add-page-numbers',
        name: '页码',
        icon: 'list-ordered',
        subtitle: '在文档中插入页码。',
      },
      {
        id: 'add-watermark',
        name: '添加水印',
        icon: 'droplets',
        subtitle: '在PDF页面上添加文本或图像水印。',
      },
      {
        id: 'add-header-footer',
        name: '页眉和页脚',
        icon: 'pilcrow',
        subtitle: '在页面顶部和底部添加文本。',
      },
      {
        id: 'invert-colors',
        name: '反转颜色',
        icon: 'contrast',
        subtitle: '创建PDF的"暗黑模式"版本。',
      },
      {
        id: 'change-background-color',
        name: '背景颜色',
        icon: 'palette',
        subtitle: '更改PDF的背景颜色。',
      },
      {
        id: 'change-text-color',
        name: '更改文本颜色',
        icon: 'type',
        subtitle: '更改PDF中文本的颜色。',
      },
      {
        id: 'sign-pdf',
        name: '签名PDF',
        icon: 'pen-tool',
        subtitle: '绘制、输入或上传您的签名。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/add-stamps.html',
        name: '添加印章',
        icon: 'stamp',
        subtitle: '使用注释工具栏向PDF添加图像印章。',
      },
      {
        id: 'remove-annotations',
        name: '删除注释',
        icon: 'eraser',
        subtitle: '删除评论、高亮和链接。',
      },
      {
        id: 'cropper',
        name: '裁剪PDF',
        icon: 'crop',
        subtitle: '修剪PDF每一页的边距。',
      },
      {
        id: 'form-filler',
        name: 'PDF表单填写',
        icon: 'square-pen',
        subtitle: '直接在浏览器中填写表单。也支持XFA表单。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/form-creator.html',
        name: '创建PDF表单',
        icon: 'file-input',
        subtitle: '使用拖放文本字段创建可填写的PDF表单。',
      },
      {
        id: 'remove-blank-pages',
        name: '删除空白页',
        icon: 'file-minus-2',
        subtitle: '自动检测并删除空白页。',
      },
    ],
  },
  {
    name: '转换为PDF',
    tools: [
      {
        id: 'image-to-pdf',
        name: '图片转PDF',
        icon: 'images',
        subtitle: '将JPG、PNG、WebP、BMP、TIFF、SVG、HEIC转换为PDF。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/jpg-to-pdf.html',
        name: 'JPG转PDF',
        icon: 'image-up',
        subtitle: '从一个或多个JPG图像创建PDF。',
      },
      {
        id: 'png-to-pdf',
        name: 'PNG转PDF',
        icon: 'image-up',
        subtitle: '从一个或多个PNG图像创建PDF。',
      },
      {
        id: 'webp-to-pdf',
        name: 'WebP转PDF',
        icon: 'image-up',
        subtitle: '从一个或多个WebP图像创建PDF。',
      },
      {
        id: 'svg-to-pdf',
        name: 'SVG转PDF',
        icon: 'pen-tool',
        subtitle: '从一个或多个SVG图像创建PDF。',
      },
      {
        id: 'bmp-to-pdf',
        name: 'BMP转PDF',
        icon: 'image',
        subtitle: '从一个或多个BMP图像创建PDF。',
      },
      {
        id: 'heic-to-pdf',
        name: 'HEIC转PDF',
        icon: 'smartphone',
        subtitle: '从一个或多个HEIC图像创建PDF。',
      },
      {
        id: 'tiff-to-pdf',
        name: 'TIFF转PDF',
        icon: 'layers',
        subtitle: '从一个或多个TIFF图像创建PDF。',
      },
      {
        id: 'txt-to-pdf',
        name: '文本转PDF',
        icon: 'file-pen',
        subtitle: '将纯文本文件转换为PDF。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/json-to-pdf.html',
        name: 'JSON转PDF',
        icon: 'file-code',
        subtitle: '将JSON文件转换为PDF格式。',
      },
      // { id: 'md-to-pdf', name: 'Markdown to PDF', icon: 'file-text', subtitle: 'Convert a Markdown file into a PDF.' },
      // { id: 'scan-to-pdf', name: 'Scan to PDF', icon: 'camera', subtitle: 'Use your camera to create a scanned PDF.' },
      // { id: 'word-to-pdf', name: 'Word to PDF', icon: 'file-text', subtitle: 'Convert .docx documents to PDF.' },
    ],
  },
  {
    name: '从PDF转换',
    tools: [
      {
        id: 'pdf-to-jpg',
        name: 'PDF转JPG',
        icon: 'file-image',
        subtitle: '将每个PDF页面转换为JPG图像。',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF转PNG',
        icon: 'file-image',
        subtitle: '将每个PDF页面转换为PNG图像。',
      },
      {
        id: 'pdf-to-webp',
        name: 'PDF转WebP',
        icon: 'file-image',
        subtitle: '将每个PDF页面转换为WebP图像。',
      },
      {
        id: 'pdf-to-bmp',
        name: 'PDF转BMP',
        icon: 'file-image',
        subtitle: '将每个PDF页面转换为BMP图像。',
      },
      {
        id: 'pdf-to-tiff',
        name: 'PDF转TIFF',
        icon: 'file-image',
        subtitle: '将每个PDF页面转换为TIFF图像。',
      },
      {
        id: 'pdf-to-greyscale',
        name: 'PDF转灰度',
        icon: 'palette',
        subtitle: '将所有颜色转换为黑白。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/pdf-to-json.html',
        name: 'PDF转JSON',
        icon: 'file-code',
        subtitle: '将PDF文件转换为JSON格式。',
      },
      // { id: 'pdf-to-markdown', name: 'PDF to Markdown', icon: 'file-pen', subtitle: 'Extract text into a Markdown file.' },
    ],
  },
  {
    name: '组织和管理',
    tools: [
      {
        id: 'ocr-pdf',
        name: 'OCR识别',
        icon: 'scan-text',
        subtitle: '使PDF可搜索和可复制。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/merge-pdf.html',
        name: '合并PDF',
        icon: 'combine',
        subtitle: '将多个PDF合并为一个文件。',
      },
      {
        id: 'alternate-merge',
        name: '交替混合页面',
        icon: 'shuffle',
        subtitle: '通过交替每个PDF的页面来合并PDF。保留书签',
      },
      {
        id: 'organize',
        name: '整理PDF',
        icon: 'grip',
        subtitle: '通过拖放重新排序页面。',
      },
      {
        id: 'duplicate-organize',
        name: '复制和整理',
        icon: 'files',
        subtitle: '复制、重新排序和删除页面。',
      },
      {
        id: 'add-attachments',
        name: '添加附件',
        icon: 'paperclip',
        subtitle: '将一个或多个文件嵌入到PDF中。',
      },
      {
        id: 'extract-attachments',
        name: '提取附件',
        icon: 'download',
        subtitle: '将PDF中的所有嵌入文件提取为ZIP。',
      },
      {
        id: 'edit-attachments',
        name: '编辑附件',
        icon: 'file-edit',
        subtitle: '查看或删除PDF中的附件。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/pdf-multi-tool.html',
        name: 'PDF多功能工具',
        icon: 'pencil-ruler',
        subtitle: '具有页面管理功能的全功能PDF编辑器。',
      },
      {
        id: 'split',
        name: '拆分PDF',
        icon: 'scissors',
        subtitle: '将页面范围提取到新的PDF中。',
      },
      {
        id: 'split-in-half',
        name: '分割页面',
        icon: 'table-columns-split',
        subtitle: '水平或垂直分割页面。',
      },
      {
        id: 'extract-pages',
        name: '提取页面',
        icon: 'ungroup',
        subtitle: '将选定的页面保存为新文件。',
      },
      {
        id: 'delete-pages',
        name: '删除页面',
        icon: 'trash-2',
        subtitle: '从文档中删除特定页面。',
      },
      {
        id: 'add-blank-page',
        name: '添加空白页',
        icon: 'file-plus-2',
        subtitle: '在PDF的任何位置插入空白页。',
      },
      {
        id: 'reverse-pages',
        name: '反转页面',
        icon: 'arrow-down-z-a',
        subtitle: '翻转文档中所有页面的顺序。',
      },
      {
        id: 'rotate',
        name: '旋转PDF',
        icon: 'rotate-cw',
        subtitle: '以90度增量旋转页面。',
      },
      {
        id: 'n-up',
        name: 'N-Up布局',
        icon: 'layout-grid',
        subtitle: '将多个页面排列到单个页面上。',
      },
      {
        id: 'combine-single-page',
        name: '合并为单页',
        icon: 'unfold-vertical',
        subtitle: '将所有页面拼接成一个连续滚动。',
      },
      {
        id: 'view-metadata',
        name: '查看元数据',
        icon: 'info',
        subtitle: '检查PDF的隐藏属性。',
      },
      {
        id: 'edit-metadata',
        name: '编辑元数据',
        icon: 'file-cog',
        subtitle: '更改作者、标题和其他属性。',
      },
      {
        id: 'pdf-to-zip',
        name: 'PDF打包为ZIP',
        icon: 'stretch-horizontal',
        subtitle: '将多个PDF文件打包到ZIP压缩包中。',
      },
      {
        id: 'compare-pdfs',
        name: '比较PDF',
        icon: 'git-compare',
        subtitle: '并排比较两个PDF。',
      },
      {
        id: 'posterize',
        name: '海报化PDF',
        icon: 'notepad-text-dashed',
        subtitle: '将大页面拆分为多个小页面。',
      },
    ],
  },
  {
    name: '优化和修复',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'src/pages/compress-pdf.html',
        name: '压缩PDF',
        icon: 'zap',
        subtitle: '减小PDF文件大小。',
      },
      {
        id: 'fix-dimensions',
        name: '修复页面尺寸',
        icon: 'ruler-dimension-line',
        subtitle: '将所有页面标准化为统一大小。',
      },
      {
        id: 'linearize',
        name: '线性化PDF',
        icon: 'gauge',
        subtitle: '优化PDF以实现快速Web查看。',
      },
      {
        id: 'page-dimensions',
        name: '页面尺寸',
        icon: 'ruler',
        subtitle: '分析页面大小、方向和单位。',
      },
      {
        id: 'remove-restrictions',
        name: '删除限制',
        icon: 'unlink',
        subtitle:
          '删除与数字签名PDF文件相关的密码保护和安全限制。',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/repair-pdf.html',
        name: '修复PDF',
        icon: 'wrench',
        subtitle: '从损坏的PDF文件中恢复数据。',
      },
    ],
  },
  {
    name: '安全PDF',
    tools: [
      {
        id: 'encrypt',
        name: '加密PDF',
        icon: 'lock',
        subtitle: '通过添加密码锁定PDF。',
      },
      {
        id: 'sanitize-pdf',
        name: '清理PDF',
        icon: 'brush-cleaning',
        subtitle: '删除元数据、注释、脚本等。',
      },
      {
        id: 'decrypt',
        name: '解密PDF',
        icon: 'unlock',
        subtitle: '通过删除密码保护解锁PDF。',
      },
      {
        id: 'flatten',
        name: '扁平化PDF',
        icon: 'layers',
        subtitle: '使表单字段和注释不可编辑。',
      },
      {
        id: 'remove-metadata',
        name: '删除元数据',
        icon: 'file-x',
        subtitle: '从PDF中删除隐藏数据。',
      },
      {
        id: 'change-permissions',
        name: '更改权限',
        icon: 'shield-check',
        subtitle: '设置或更改PDF的用户权限。',
      },
    ],
  },
];
